title: Lin Fan
description: ""
subtitle: >
  PhD candidate in Economics, LSE<div style="height:0px;"></div>
logo: /assets/img/lin_fan_23-24-648x648.jpg
#description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics: true
#theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
